title: MOCA Spike 150 - Running Forward With Our Stories
tagline: Running Forward With Our Stories
author: MOCA Spike 150
email: mocaspike150@mocanyc.org
company_name:  Museum of Chinese in America
excerpt_separator: <!--more-->
url: "https://www.mocaspike150.org"
timezone: America/New_York
contact_email: rshih@mocanyc.org

collections:
  news:
    output: true
    permalink: /:collection/:path
  events:
    output: true
    permalink: /:collection/:path
  stories:
    output: true
    permalink: /:collection/:path

exclude: 
- Dockerfile
- docker-compose.yml
- node_modules
- package.json
- package-lock.json
- README.md

show_excerpts: true
