title: MOCA Spike 150 - Running Forward With Our Stories 
author: MOCA Spike 150
email: rshih@mocanyc.org
description: > 
  2019 marks the 150th anniversary of the completion of the transcontinental railroad.  
  The “MOCA Spike 150 - Running Forward with Our Stories!”  initiative will honor the thousands of
  Chinese workers responsible for this great milestone in American History as well as explore 
  the Chinese diaspora throughout America.  
theme: minima

plugins:
 - jekyll-seo-tag
 
google_analytics: 'UA-134524506-1'
