title: MOCA Spike 150 - Running Forward With Our Stories
tagline: Running Forward With Our Stories
author: MOCA Spike 150
email: mocaspike150@mocanyc.org
address: >
  <address>
  <ul>
  <li>Museum of Chinese in America</li>
  <li>215 Centre Street New York, NY 10013</li>
  <li>855-955-MOCA</li>
  </ul>
  </address>
remote_theme: mocaspike150/mocaspike150-theme
description: > 
  2019 marks the 150th anniversary of the completion of the transcontinental railroad.  
  The “MOCA Spike 150 - Running Forward with Our Stories!”  initiative will honor the thousands of
  Chinese workers responsible for this great milestone in American History as well as explore 
  the Chinese diaspora throughout America.  
url: "https://www.mocaspike150.org"
timezone: America/New_York


collections:
  events:
    output: true

plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
 
minima:
  social_links:
    twitter: mocanyc
    instagram: mocanyc
    youtube: mocanyc
    facebook: mocanyc
    flickr: mocamuseum
    vimeo: user4422249
    
fb: 
    appid: 2562680747076655

twitter:
    username: mocanyc

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/moca-spike-150-share.jpg
      
google_analytics: 'UA-134524506-2'

exclude: 
- Dockerfile
- docker-compose.yml
- README.md
- Gemfile
- Gemfile.lock
- mocaspike150-theme.gemspec
