title: MOCA Spike 150 - Running Forward With Our Stories 
author: MOCA Spike 150
email: mocaspike150@mocanyc.org
remote_theme: mocaspike150/mocaspike150-theme
description: > 
  2019 marks the 150th anniversary of the completion of the transcontinental railroad.  
  The “MOCA Spike 150 - Running Forward with Our Stories!”  initiative will honor the thousands of
  Chinese workers responsible for this great milestone in American History as well as explore 
  the Chinese diaspora throughout America.  

url: "https://mocaspike150.github.io"

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
 
minima:
  social_links:
    twitter: mocanyc
    instagram: mocanyc
    youtube: mocanyc
    facebook: mocanyc
    flickr: mocamuseum
    vimeo: user4422249

google_analytics: 'UA-134524506-2'

