title: MOCA Spike 150 - Running Forward With Our Stories
tagline: Running Forward With Our Stories
author: MOCA Spike 150
email: mocaspike150@mocanyc.org
company_name:  Museum of Chinese in America
excerpt_separator: <!--more-->
url: "https://www.mocaspike150.org"
timezone: America/New_York
contact_email: rshih@mocanyc.org
image: https://www.mocaspike150.org/assets/images/moca-spike-150-share.jpg

future: true

collections:
  posts:
    output: true
    permalink: /:collection/:path
  events:
    output: true
    permalink: /:collection/:path
  stories:
    output: true
    permalink: /:collection/:path

exclude: 
- Dockerfile
- docker-compose.yml
- node_modules
- package.json
- package-lock.json
- README.md
- app

show_excerpts: true

plugins:
  - jekyll-redirect-from

google_analytics: 'UA-135436278-1'
